language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - nosetests
env:
  - DJANGO_SETTINGS_MODULE=domotina.settings
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database domotina;' -U postgres
  - python manage.py syncdb --noinput
notifications:
  email:
    recipients:
      - le.florez602@uniandes.edu.co
    on_success: always
    on_failure: never
